export ZSH="$HOME/.oh-my-zsh"
ZSH_THEME="robbyrussell"
plugins=(git colored-man-pages colorize pip python brew macos zsh-autosuggestions zsh-syntax-highlighting dotenv)
source $ZSH/oh-my-zsh.sh

#test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"
PATH=~/bin:$PATH

export GPG_TTY=$(tty)

# Generated by Hermit; START; DO NOT EDIT.
eval "$(test -x $HOME/bin/hermit && $HOME/bin/hermit shell-hooks --print --zsh)"
# Generated by Hermit; END; DO NOT EDIT.
