# CLI tools
brew "git"
brew "ripgrep"
brew "fd"
brew "dockutil"
brew "mas"
brew "bitwarden-cli"
brew "gh"
brew "jq"
brew "croc"
brew "gnupg"
brew "azure-cli"

# ESP-IDF / Espressif tooling
tap "espressif/eim"
brew "libgcrypt"
brew "glib"
brew "pixman"
brew "sdl2"
brew "libslirp"
brew "dfu-util"
brew "cmake"
brew "python"
brew "eim"

# CLI tools (casks)
tap "gussy/tap"
cask "gussy/tap/cmt"

# Terminal Setup
cask "ghostty"
cask "font-monaspace"
tap "jandedobbeleer/oh-my-posh"
cask "jandedobbeleer/oh-my-posh/oh-my-posh"
brew "zoxide"
brew "fzf"

# GUI Applications
cask "visual-studio-code"
cask "android-studio"
cask "gitbutler"
cask "claude"
cask "tailscale-app"
cask "windows-app"
cask "discord"
cask "autodesk-fusion"
cask "bambu-studio"
cask "docker"
cask "utm"
cask "balenaetcher"
cask "crystalfetch"
cask "obs"
cask "notion"
cask "chatgpt"
cask "codex-app"
cask "affinity"
cask "lightburn"
cask "android-commandlinetools"
cask "temurin@17"
#cask "kicad"
tap "5aaee9/kicad-nightly"
cask "kicad-nightly"
